import type { Metadata } from "next";
import { Syne, EB_Garamond, Outfit, Dancing_Script } from "next/font/google";
import "./globals.css";
import { Footer } from "@/modules/landingPage/footer";
import { ConnectSection } from "@/modules/landingPage/connect-section";

const syne = Syne({
  variable: "--font-heading",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-serif",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-handwriting",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${syne.variable} ${ebGaramond.variable} ${outfit.variable} ${dancingScript.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ConnectSection />
        <Footer />
      </body>
    </html>
  );
}
